name: Snyk Scan and Deploy
on:
  push:
    branches:
      - main
jobs:
  snyk-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node (required for Snyk CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high
      - name: Deploy to AWS
        if: success()   # only runs if Snyk passes
        run: |
          echo "Deploying to AWS..."
 
